name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Build the app
        run: make prod_build_bundle

      - name: Change owner of all files in dist to current user
        run: sudo chown -R $(id -u):$(id -g) dist

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
